# Generated by Django 4.0.4 on 2022-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianss',
            name='DOB',
            field=models.DateField(),
        ),
    ]
