# Generated by Django 4.0.4 on 2022-08-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0003_remove_technicianss_dob_technicianss_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='technicianss',
            new_name='technician',
        ),
    ]
