# Generated by Django 4.0.4 on 2022-08-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electro', '0004_rename_technicianss_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='connect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
