# Generated by Django 4.0.4 on 2022-11-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0007_customer_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='request_Type',
            field=models.CharField(choices=[('laptop', 'LAPTOP'), ('tv', 'TV'), ('smart phone', 'SMART PHONE'), ('wifi', 'WIFI'), ('ac', 'AC')], default=' ', max_length=50),
        ),
    ]
