# Generated by Django 4.0.4 on 2022-11-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0008_alter_customer_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='request_Type',
            field=models.CharField(choices=[('--PLEASE CHOOSE A SERVICE--', '--Please choose a service--'), ('laptop', 'LAPTOP'), ('tv', 'TV'), ('smart phone', 'SMART PHONE'), ('wifi', 'WIFI'), ('ac', 'AC')], default=' ', max_length=50),
        ),
    ]
