# Generated by Django 4.0.4 on 2022-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0009_alter_customer_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-22 05:33'),
            preserve_default=False,
        ),
    ]
