# Generated by Django 4.0.4 on 2022-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0010_customer_request_cdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_request',
            name='cdate',
        ),
    ]
