# Generated by Django 4.0.4 on 2022-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0011_remove_customer_request_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-12 03:33'),
            preserve_default=False,
        ),
    ]
