# Generated by Django 4.0.4 on 2022-11-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0012_customer_request_cdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_request',
            name='request_ID',
        ),
        migrations.AddField(
            model_name='customer_request',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
