# Generated by Django 4.0.4 on 2022-11-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0013_remove_customer_request_request_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
