# Generated by Django 4.0.4 on 2022-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0018_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
