# Generated by Django 4.0.4 on 2022-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0020_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='boss',
        ),
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(default='shahul', max_length=20),
            preserve_default=False,
        ),
    ]
